In [4]:
import os

# Verificar si el archivo existe en la ruta especificada
print(os.path.exists('../retail_sales_dataset.csv')) 

True


In [30]:
import numpy as np

# Función para cargar los datos del archivo CSV
def cargar_datos(ruta_archivo):
    # Cargar los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', skip_header=1)
    return datos

if __name__ == "__main__":
    # Ruta del archivo CSV
    ruta_archivo = '../retail_sales_dataset.csv'
    
    # Cargar los datos
    datos = cargar_datos(ruta_archivo)
    
    # Imprimir los primeros registros para inspección
    print(datos)

[[   1.   nan   nan ...    3.   50.  150.]
 [   2.   nan   nan ...    2.  500. 1000.]
 [   3.   nan   nan ...    1.   30.   30.]
 ...
 [ 998.   nan   nan ...    4.   25.  100.]
 [ 999.   nan   nan ...    3.   50.  150.]
 [1000.   nan   nan ...    4.   30.  120.]]


In [31]:
total_ventas = np.sum(datos[:, -2:], axis=0)  # Sumar las columnas correspondientes a ventas
print("Total de Ventas por Categoría:", total_ventas)

Total de Ventas por Categoría: [179890. 456000.]


In [33]:
promedio_ventas = np.nanmean(datos[:, -2:], axis=0)  # Promedio de ventas
print("Promedio de Ventas Diarias por Categoría:", promedio_ventas)

Promedio de Ventas Diarias por Categoría: [179.89 456.  ]


In [34]:
# Identificar las categorías con mayores y menores ventas
max_ventas = np.max(total_ventas)
min_ventas = np.min(total_ventas)
print("Categoría con mayores ventas:", max_ventas)
print("Categoría con menores ventas:", min_ventas)

Categoría con mayores ventas: 456000.0
Categoría con menores ventas: 179890.0


In [9]:
"""Agregue esta operacion para obtener los nombres de columnas"""
import pandas as pd

def cargar_datos(ruta_archivo):
    # Cargar los datos del archivo CSV utilizando pandas
    datos = pd.read_csv(ruta_archivo)
    return datos

# Ruta del archivo (deberás poner tu propia ruta)
ruta_archivo = '../retail_sales_dataset.csv'

# Cargar los datos
df = cargar_datos(ruta_archivo)

# Convertir el DataFrame a un array de NumPy si es necesario
data_numpy = df.to_numpy()

# Ver los nombres de las columnas
print("Nombres de las columnas:", df.columns)

# Visualizar los datos como un array NumPy
print("\nArray de NumPy:\n", data_numpy)


Nombres de las columnas: Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

Array de NumPy:
 [[1 '2023-11-24' 'CUST001' ... 3 50 150]
 [2 '2023-02-27' 'CUST002' ... 2 500 1000]
 [3 '2023-01-13' 'CUST003' ... 1 30 30]
 ...
 [998 '2023-10-29' 'CUST998' ... 4 25 100]
 [999 '2023-12-05' 'CUST999' ... 3 50 150]
 [1000 '2023-04-12' 'CUST1000' ... 4 30 120]]


In [11]:
import numpy as np

# Función para cargar los datos
def cargar_datos(ruta_archivo):
    # Cargar los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', dtype=str, encoding='utf-8', skip_header=1)
    return datos

# Ruta del archivo CSV (ajusta esta ruta)
ruta_archivo = '../retail_sales_dataset.csv'

# Cargar los datos
datos = cargar_datos(ruta_archivo)

# Verifica si los datos se cargaron como una matriz bidimensional
print("Array de NumPy (primeras filas):\n", datos[:5])

# Verifica las dimensiones del array
print("Dimensiones del array:", datos.shape)

# Filtrar los datos por una categoría de producto específica, en este caso 'Beauty'
# La columna 'Product Category' está en el índice 5
categoria_especifica = datos[datos[:, 5] == 'Beauty']

# Mostrar los datos filtrados por la categoría 'Beauty'
print("Datos filtrados (Categoría 'Beauty'):\n", categoria_especifica)


Array de NumPy (primeras filas):
 [['1' '2023-11-24' 'CUST001' 'Male' '34' 'Beauty' '3' '50' '150']
 ['2' '2023-02-27' 'CUST002' 'Female' '26' 'Clothing' '2' '500' '1000']
 ['3' '2023-01-13' 'CUST003' 'Male' '50' 'Electronics' '1' '30' '30']
 ['4' '2023-05-21' 'CUST004' 'Male' '37' 'Clothing' '1' '500' '500']
 ['5' '2023-05-06' 'CUST005' 'Male' '30' 'Beauty' '2' '50' '100']]
Dimensiones del array: (1000, 9)
Datos filtrados (Categoría 'Beauty'):
 [['1' '2023-11-24' 'CUST001' ... '3' '50' '150']
 ['5' '2023-05-06' 'CUST005' ... '2' '50' '100']
 ['6' '2023-04-25' 'CUST006' ... '1' '30' '30']
 ...
 ['994' '2023-12-18' 'CUST994' ... '2' '500' '1000']
 ['997' '2023-11-17' 'CUST997' ... '3' '30' '90']
 ['998' '2023-10-29' 'CUST998' ... '4' '25' '100']]


In [12]:
import numpy as np

# Función para cargar los datos
def cargar_datos(ruta_archivo):
    # Cargar los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', dtype=str, encoding='utf-8', skip_header=1)
    return datos

# Ruta del archivo CSV (ajusta esta ruta)
ruta_archivo = '../retail_sales_dataset.csv'

# Cargar los datos
datos = cargar_datos(ruta_archivo)

# Verifica las dimensiones del array
print("Dimensiones del array:", datos.shape)

# Convertir columnas específicas a valores numéricos (age, quantity, price, total amount)
# La columna 4 es 'Age', la 6 es 'Quantity', la 7 es 'Price per Unit', y la 8 es 'Total Amount'

# Convertir estas columnas a formato numérico (float o int)
age = datos[:, 4].astype(float)
quantity = datos[:, 6].astype(float)
price_per_unit = datos[:, 7].astype(float)
total_amount = datos[:, 8].astype(float)

# **Operaciones**
# 1. Suma: suma de 'Quantity' y 'Price per Unit'
suma = quantity + price_per_unit

# 2. Resta: diferencia entre 'Total Amount' y 'Price per Unit'
resta = total_amount - price_per_unit

# 3. Multiplicación: producto de 'Quantity' y 'Price per Unit'
multiplicacion = quantity * price_per_unit

# 4. División: división de 'Total Amount' entre 'Quantity' (evitar división por 0)
division = np.divide(total_amount, quantity, where=quantity != 0)

# Mostrar resultados
print("Suma (Quantity + Price per Unit):\n", suma[:5])  # Mostrar las primeras 5 filas
print("Resta (Total Amount - Price per Unit):\n", resta[:5])  # Mostrar las primeras 5 filas
print("Multiplicación (Quantity * Price per Unit):\n", multiplicacion[:5])  # Mostrar las primeras 5 filas
print("División (Total Amount / Quantity):\n", division[:5])  # Mostrar las primeras 5 filas

# Estadísticas adicionales
print("\nEstadísticas adicionales:")
print("Suma total de 'Quantity':", np.sum(quantity))
print("Precio promedio por unidad:", np.mean(price_per_unit))
print("Total promedio por transacción:", np.mean(total_amount))
print("Rango de edades:", np.min(age), "-", np.max(age))


Dimensiones del array: (1000, 9)
Suma (Quantity + Price per Unit):
 [ 53. 502.  31. 501.  52.]
Resta (Total Amount - Price per Unit):
 [100. 500.   0.   0.  50.]
Multiplicación (Quantity * Price per Unit):
 [ 150. 1000.   30.  500.  100.]
División (Total Amount / Quantity):
 [ 50. 500.  30. 500.  50.]

Estadísticas adicionales:
Suma total de 'Quantity': 2514.0
Precio promedio por unidad: 179.89
Total promedio por transacción: 456.0
Rango de edades: 18.0 - 64.0
